
variable "vpc_id" {}
variable "route_table_public_id" {}
variable "route_table_private_name" {}
variable "public_subnet1_cidr" {}
variable "public_subnet2_cidr" {}
variable "private_subnet1_cidr" {}
variable "private_subnet2_cidr" {}
variable "public_subnet1_az" {}
variable "public_subnet2_az" {}
variable "private_subnet1_az" {}
variable "private_subnet2_az" {}
variable "public_subnet1_name" {}
variable "public_subnet2_name" {}
variable "private_subnet1_name" {}
variable "private_subnet2_name" {}
variable "sg_name" {}
variable "sg_description" {}
variable "http_description" {}
variable "allow_http_cidr" {}
variable "egress_cidr" {}
variable "natgw_name" {}
variable "natgw_eip_name" {}